[tox]
envlist = py39, py310, py311, py312, py313

[testenv]
setenv =
    QT_QPA_PLATFORM = offscreen
    PTO_DEVICE_INDEX = 0
    PTO_N_WORK_UNITS = 128
    PTO_MAX_MEMORY_MB = 1024
commands =
    python -m unittest discover -v
