name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install OpenCL dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pocl-opencl-icd ocl-icd-opencl-dev gcc clinfo
          clinfo

      - name: Install OpenGL, EGL, and OSMesa
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libegl1-mesa-dev \
            libosmesa6-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            freeglut3-dev \
            xvfb

      - name: Install tox
        run: pip install tox

      - name: Run tests
        run: tox -e py${{ matrix.python-version }}
